[package]
name = "rusty_cookie_monster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ini = "1.3.0"
directories = "5.0.1"
chrono = "0.4.25"
gethostname = "0.4.3"
rusqlite = "0.29.0"
